修复当目录已存在时,同步PHP源码在指定目录又创建子文件夹
swoole/swoole-cli pull request #787
Opened 2024-09-22 05:51 UTC by maxiaozhi

2024-09-23 08:42 UTC, matyhtf requested changes

2024-09-23 08:42 UTC, matyhtf commented on sync-source-code.php
> -    cp -rf $SRC/sapi/cli/ps_title.c ./sapi/cli
这里的修改存在问题，cli 目录不同步

2024-09-24 01:06 UTC, maxiaozhi commented on sync-source-code.php
> -    cp -rf $SRC/sapi/cli/ps_title.c ./sapi/cli
> 这里的修改存在问题，cli 目录不同步
如果不同步cli目录的话,当版本差异较大,编译会报错的,有些类型都改变了
cli目录主要是有sapi/cli/php_cli.c这个文件需要人工再处理,添加swoole相关的引用,sapi/cli/php_cli_server.c这个要把PHP_FUNCTION(apache_request_headers)函数前面添加static就好了
请问具体还有哪些问题?

2024-10-06 08:02 UTC, jingjingxyk commented
如何复现" 修复当目录已存在时,同步PHP源码在指定目录又创建子文件夹 " 这个问题？

我执行的命令是：
```

./bin/runtime/php -c ./bin/runtime/php.ini  sync-source-code.php --action run

```
https://github.com/jingjingxyk/swoole-cli/compare/main...jingjingxyk:swoole-cli:feature-compare-code

2024-10-06 12:11 UTC, maxiaozhi commented
> @maxiaozhi 如何复现" 修复当目录已存在时,同步PHP源码在指定目录又创建子文件夹 " 这个问题？
> 
> 我执行的命令是：
> 
> ```
> 
> ./bin/runtime/php -c ./bin/runtime/php.ini  sync-source-code.php --action run
> ```
> 
> [jingjingxyk/swoole-cli@main...jingjingxyk:swoole-cli:feature-compare-code](https://github.com/jingjingxyk/swoole-cli/compare/main...jingjingxyk:swoole-cli:feature-compare-code)

该问题应该只在linux下会存在,我尝试在alpine容器中以及deepin下测试,均存在同类问题,但在macos下测却没有问题

2024-10-06 12:21 UTC, jingjingxyk commented
> > @maxiaozhi 如何复现" 修复当目录已存在时,同步PHP源码在指定目录又创建子文件夹 " 这个问题？
> > 我执行的命令是：
> > ```
> > 
> > ./bin/runtime/php -c ./bin/runtime/php.ini  sync-source-code.php --action run
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [jingjingxyk/swoole-cli@main...jingjingxyk:swoole-cli:feature-compare-code](https://github.com/jingjingxyk/swoole-cli/compare/main...jingjingxyk:swoole-cli:feature-compare-code)
> 
> 该问题应该只在linux下会存在,我尝试在alpine容器中以及deepin真机下测试,均存在同类问题,但在macos下测却没有问题,windows下没有做测试

原来如此，我试一下

2024-10-07 18:11 UTC, jingjingxyk commented
> > @maxiaozhi 如何复现" 修复当目录已存在时,同步PHP源码在指定目录又创建子文件夹 " 这个问题？
> > 我执行的命令是：
> > ```
> > 
> > ./bin/runtime/php -c ./bin/runtime/php.ini  sync-source-code.php --action run
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [jingjingxyk/swoole-cli@main...jingjingxyk:swoole-cli:feature-compare-code](https://github.com/jingjingxyk/swoole-cli/compare/main...jingjingxyk:swoole-cli:feature-compare-code)
> 
> 该问题应该只在linux下会存在,我尝试在alpine容器中以及deepin真机下测试,均存在同类问题,但在macos下测却没有问题,windows下没有做测试

linux 与macos  `cp -r` 区别
https://twilblog.github.io/macos/linux/cp/copy/2017/02/03/macos-unix-cp-madness.html

解决办法就是加一个点

2024-10-09 03:09 UTC, closed without merging